// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3FMG_bHpd9RUY3I4zJJg_v77aVkHSLmc',
    appId: '1:899945822082:web:d597a86e7e3d93697ec19b',
    messagingSenderId: '899945822082',
    projectId: 'woosin-work',
    authDomain: 'woosin-work.firebaseapp.com',
    databaseURL: 'https://woosin-work-default-rtdb.firebaseio.com',
    storageBucket: 'woosin-work.firebasestorage.app',
    measurementId: 'G-6GLEYHLVJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3Wysysyf89ZoFADjdLVQZT_trX8TgFFg',
    appId: '1:899945822082:android:c358630bff2cb5a97ec19b',
    messagingSenderId: '899945822082',
    projectId: 'woosin-work',
    databaseURL: 'https://woosin-work-default-rtdb.firebaseio.com',
    storageBucket: 'woosin-work.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtrswBzsZBjFxLEIG9A5x3a4tiz6tuyXQ',
    appId: '1:899945822082:ios:4082a495bc4168457ec19b',
    messagingSenderId: '899945822082',
    projectId: 'woosin-work',
    databaseURL: 'https://woosin-work-default-rtdb.firebaseio.com',
    storageBucket: 'woosin-work.firebasestorage.app',
    iosBundleId: 'com.example.workforceManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtrswBzsZBjFxLEIG9A5x3a4tiz6tuyXQ',
    appId: '1:899945822082:ios:4082a495bc4168457ec19b',
    messagingSenderId: '899945822082',
    projectId: 'woosin-work',
    databaseURL: 'https://woosin-work-default-rtdb.firebaseio.com',
    storageBucket: 'woosin-work.firebasestorage.app',
    iosBundleId: 'com.example.workforceManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3FMG_bHpd9RUY3I4zJJg_v77aVkHSLmc',
    appId: '1:899945822082:web:f18d5178560e49017ec19b',
    messagingSenderId: '899945822082',
    projectId: 'woosin-work',
    authDomain: 'woosin-work.firebaseapp.com',
    databaseURL: 'https://woosin-work-default-rtdb.firebaseio.com',
    storageBucket: 'woosin-work.firebasestorage.app',
    measurementId: 'G-K0TJ1ZLT6C',
  );
}
